spring.application.name=Frameworks2

spring.datasource.url=jdbc:mysql://${{MySQL.MYSQLHOST}}:${{MySQL.MYSQLPORT}}/${{MySQL.MYSQLDATABASE}}
spring.datasource.username=${{MySQL.MYSQLUSER}}
spring.datasource.password=${{MySQL.MYSQLPASSWORD}}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
